GET http://localhost:3000/

### 获取所有短链接

GET http://localhost:3000/url

### 创建一个短链接

POST http://localhost:3000/url
Content-Type: application/json

{
  "redirect": "https://abei.me",
  "title": "Abei",
  "description": "Abei is my personal website"
}


### 访问短链

GET http://localhost:3000/888999


### 更新短链信息

PATCH http://localhost:3000/url/5Bbpgv
Content-Type: application/json

{
  "redirect": "https://abei.me",
  "title": "Abei",
  "description": "Abei is my personal website2"
}

### 删除短链

DELETE  http://localhost:3000/url/tQ-Gos