GET http://localhost:3000/

###

GET http://localhost:3000/url

### 创建一个短链接

POST http://localhost:3000/url
Content-Type: application/json

{
  "redirect": "https://www.google.com",
  "title": "Google",
  "description": "Google is a search engine company"
}
