# - 用于表示数组或列表项
services:
  nestjs_starter_postgres:
    image: postgres:alpine
    container_name: nestjs_starter_postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - nestjs_starter_postgres_data:/var/lib/postgresql/data

  nestjs_starter_redis:
    image: redis:alpine
    container_name: nestjs_starter_redis
    ports:
      - '6400:6379'
    volumes:
      - nestjs_starter_redis_data:/data

networks:
  default:
    name: nestjs_starter

volumes:
  nestjs_starter_postgres_data:
  nestjs_starter_redis_data:
